[package]
name = "spl-counter"
version = "1.0.0"
description = "Solana Program counter Example"
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
byteorder = "1.3"
solana-program = "1.5.15"

[dev-dependencies]
solana-program-test = "1.5.15"
solana-sdk = "1.5.15"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]